
export const ACTION_TYPES = {
    // Category
    ADD_CATEGORY: "ADD_CATEGORY",
    UPDATE_CATEGORY: "UPDATE_CATEGORY",
    DELETE_CATEGORY: "DELETE_CATEGORY",

    // Task
    ADD_TASK: "ADD TASK",
    UPDATE_TASK: "UPDATE_TASK",
    DELETE_TASK: "DELETE_TASK",
    TOGGLE_TASK_COMPLETION: "TOGGLE_TASK_COMPLETION",

    // UI
    CATEGORY_SELECTED: "CATEGORY_SELECTED",
    TASK_SELECTED: "TASK_SELECTED"
}